# Generated by Django 3.2.7 on 2021-10-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='user_profile_pictures/profile_pic', upload_to='user_profile_pictures/'),
        ),
    ]
