# Generated by Django 3.2.7 on 2021-10-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='user_profile_pictures/default_user.jpeg', upload_to='user_profile_pictures/'),
        ),
    ]
