# Generated by Django 3.2.7 on 2021-11-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordreset'),
        ('users', '0004_alter_user_profile_pic'),
    ]

    operations = [
    ]
