version: "3.9"
   
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres