# Generated by Django 3.2.7 on 2021-11-05 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(blank=True, max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('logo', models.ImageField(blank=True, default='event_logos/default_event.png', null=True, upload_to='event_logos/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(default=events.models.OrganizerEventModel.generateUniqueCode, max_length=10, null=True, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='eventteammodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_related_event', to='events.organizereventmodel'),
        ),
        migrations.AddField(
            model_name='eventteammodel',
            name='hold_teammates',
            field=models.ManyToManyField(related_name='hold_teammates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventteammodel',
            name='interested',
            field=models.ManyToManyField(related_name='event_team_interested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventteammodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventteammodel',
            name='teammates',
            field=models.ManyToManyField(related_name='event_teammates', to=settings.AUTH_USER_MODEL),
        ),
    ]
