# Generated by Django 3.2.7 on 2021-11-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211105_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizereventmodel',
            name='owner',
        ),
    ]
