# Generated by Django 3.2.6 on 2021-08-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile',
            field=models.JSONField(default=None),
        ),
    ]
