# Generated by Django 3.2.6 on 2021-08-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeal', '0002_userdata_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile',
            field=models.JSONField(default={}),
        ),
    ]
